server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456789
    url: jdbc:sqlserver://192.168.100.209:1433;DatabaseName=MES
    # thymeleaf 相关设置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    cache: false
    check-template: true

logging:
  level:
    net.stopno.xingda.demo: debug
